baseURL = "https://mattn.qzz.io/"
title = "ã†ã§ãŸã¾ã”"
#paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ã†ã§ãŸã¾ã”"
description = "ã†ã§ãŸã¾ã” description"
keywords = [ "ã†ã§ãŸã¾ã”" ]
author = "Me"
images = [ "/favicon.png" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "/favicon.png"
  favicon16x16 = "/favicon.png"
  favicon32x32 = "/favicon.png"
  apple_touch_icon = "/favicon.png"
  safari_pinned_tab = "/favicon.png"

  [params.label]
  text = "Home"
  icon = "/favicon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "ã†ã§ãŸã¾ã”"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "ã†ã§ãŸã¾ã” ğŸ¥š"
  Content = "ãŠãŠãã«ï¼ã‚ã—ã‚„ã§"

  [[params.socialIcons]]
  name = "x"
  url = "https://x.com/mattn_jp"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/720391/mattn"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/mattn"

#[params.analytics.google]
#SiteVerificationTag = "XYZabc"
#
#[params.analytics.bing]
#SiteVerificationTag = "XYZabc"

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "mattn.qzz.io"
name = "mattn.qzz.io"
url = "https://mattn.qzz.io"
weight = 30

[markup.highlight]
noClasses = false

[privacy]
  [privacy.googleAnalytics]
    disable = true
    respectDoNotTrack = false
